### ISSUE TITLE
Extended diff produces unexpected results

### ISSUE THREAD

**Issue by darrarski** [tonyarnold/Differ#18]
I am not sure if this is an issue, or I just don't understand how it works. I am really confused and looking for help, thanks in advance for your support.

I have an array of `Int`, from 1 to 4. I swap first and last elements:

```swift
let old = [1, 2, 3, 4]
let new = [4, 2, 3, 1]
old.diff(new).elements // [D(0), I(0), D(3), I(3)]
old.extendedDiff(new).elements // [M(0,3), M(3,0)]
```

I can do the same for array of `Int` with more elements:

```swift
let old = [1, 2, 3, 4, 5]
let new = [5, 2, 3, 4, 1]
old.diff(new).elements // [D(0), I(0), D(4), I(4)]
old.extendedDiff(new).elements // [M(0,4), M(4,0)]
```

However, for array with only three elements, the result is something that I don't understand:

```swift
let old = [1, 2, 3]
let new = [3, 2, 1]
old.diff(new).elements // [D(0), D(1), I(1), I(2)]
old.extendedDiff(new).elements // [M(0,2), M(1,1)]
```

Is it a bug or expected behavior?

**Comment by tonyarnold** [comment]
The final `M(1,1)` looks like a bug. I would have expected it to be `M(0,1)`, but I probably need to think about it a little.

**Comment by wokalski** [comment]
Hey, I know it's confusing. It's because of the difference between diff vs patch. The trick is that diff is not ordered. `D(0)` means remove the element that's initially on index `0`. It doesn't say remove element that's currently on index `0`.

Similarly, `M(1,1)` means, move element from index `1` in the in the initial sequence to index `1` in the final sequence.

And here comes the feature I've worked on for hours but probably nobody ever used - patch. `Patch` allows you to create an ordered list of steps from unordered diff.

**Comment by darrarski** [comment]
Hey, @wokalski I am using `patch` frequently and I am really like it :-) I appreciate your work!

Thanks for explanation, but I still don't get it. I am aware of diffs not being ordered. But just take a look at `old` and `new` arrays and the extended diff that is produced:

```swift
let old = [1, 2, 3]
let new = [3, 2, 1]
old.extendedDiff(new).elements // [M(0,2), M(1,1)]
``` 

- `M(0,2)` seems ok, as `1` was moved from index 0 (in `old`) to index 2 (in `new`) 
- `M(1,1)` would mean that `2` was moved from index 1 (in `old`) to index 1 (in `new`)

That is correct, but not sure how to interpret it. There is no diff element that tells about `3` being moved from index 2 (in `old`) to index 0 (in `new`). 

If you test this with array that contains more than 3 items, you will get this output:

```
[M(0,x), M(x,0)] where x == array.count - 1
```

However, for array with only three items the output is different, and that's what I am trying to understand.

**Comment by wokalski** [comment]
The diff, contains the minimal amount of steps and extendedDiff is just the derivative of it. Because of how the algorithm works the 3 remains where it was so it's not included in the diff at all. In this case you can think of three as a basis for the algorithm. If we ran it from the end, `1` would be the "basis" element. 

I know it's all confusing so I insist - please ask further questions.

**Comment by darrarski** [comment]
I see it now,

1. initial / old: `[1, 2, 3]`
2. `M(0,2)` - move element at initial index 0 (`1`) to index 2
3. `[2, 3, 1]`
4. `M(1,1)` - move element at initial index 1 (`2`) to index 1
5. result / new: `[3, 2, 1]`

the same swap in four-elements array:

1. initial / old: `[1, 2, 3, 4]`
2. `M(0,3)` - move element at initial index 0 (`1`) to index 3
3. `[2, 3, 4, 1]`
4. `M(3,0)` - move element at initial index 3 (`4`) to index 0
5. result / new: `[4, 3, 2, 1]`

Thanks for explanation. I am closing the issue.

**Comment by darrarski** [comment]
@wokalski recently I used it for updating `NSTableView` rows in macOS app. It was also useful for me when developing iOS apps.
