### ISSUE TITLE
Does it work asynchronously?

### ISSUE THREAD

**Issue by ZQutui** [tonyarnold/Differ#63]
I tried to use code like
DispatchQueue.global().async {
    ....patch(from:to:)...
}
and it always throws a "EXC_BAD_ACCESS" error with long texts(4000 elements each). What can I do about it?

**Comment by tkrajacic** [comment]
My guess is that you are trying to update a table view or collection view in there? You must only do this on the main queue. This would have nothing to do with Differ itself.

Try enabling the thread sanitizer in Xcode when running your app, it might tell you more.

**Comment by ZQutui** [comment]
Nope, it doesn't use any UI elements in there. it's literally just
```
 DispatchQueue.global().async {
            patch(from: revisedText, to: originalText, sort: sortPredicate)
        }
```
revisedText and originalText are arrays containing Substrings

**Comment by tonyarnold** [comment]
Is there any chance you can provide a sample project demonstrating the issue? I’m happy to take a look if you can.

**Comment by ZQutui** [comment]
I created a project here https://github.com/ZQutui/IssueWithDiffer. I found out that this issue occurs only when you specify sort property while using patch function, without sort property it works perfectly fine

**Comment by tonyarnold** [comment]
Thanks @ZQutui - the problem reproduced locally using the project you provided. I'll have a look at what's happening as soon as I have some free time to sink into this.

**Comment by ZQutui** [comment]
What library or temporary workaround do you know? I need this sorting. Sorting just a diffed array  doesn't help. Other libraries doesn't provide this capability or I couldn't find it.

**Comment by jenox** [comment]
Looks like the problem here is a stack overflow in large data sets due to recursive implementations of various methods operating on linked lists, namely

```swift
func array() -> Array<T>
```
and
```swift
func shiftPatchElement<T>(node: DoublyLinkedList<SortedPatchElement<T>>)
```

I'm not familiar with the internals of the library yet, so I can't tell you why this is happening only if you specify a custom sort descriptor.

As for why this only happens on background threads: I have no clue. Both the main thread and a background thread report a `Thread.current.stackSize` of `524288` on my machine. But I can get a background thread to crash with a simple recursive function that is 10k deep, while that doesn't work on the main thread.
